# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    # csrf_protection est activé par défaut depuis Symfony 7.2
    
    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: true
        cookie_samesite: lax
        
    http_method_override: false
    handle_all_throwables: true

    #esi: true
    #fragments: true

    cache:
        app: cache.adapter.apcu
        system: cache.adapter.system

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
