security:
    # Configuration du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 12

    # Configuration des providers utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: userEmail

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_DEVELOPER: ROLE_USER
        ROLE_LEAD_DEVELOPER: ROLE_DEVELOPER
        ROLE_PROJECT_MANAGER: ROLE_LEAD_DEVELOPER
        ROLE_RESPONSABLE: ROLE_PROJECT_MANAGER
        ROLE_ADMIN: [ROLE_RESPONSABLE, ROLE_ALLOWED_TO_SWITCH]

    # Configuration des pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: app_auth
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès global
    access_control:
        # Authentification
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        
        # Pages générales pour utilisateurs connectés
        - { path: ^/parameter/generaux, roles: ROLE_USER }
        - { path: ^/parameter/about, roles: ROLE_USER }
        
        # Gestion des utilisateurs
        - { path: ^/parameter/users/, roles: [ROLE_PROJECT_MANAGER, ROLE_RESPONSABLE, ROLE_ADMIN] }
        
        # Gestion des clients
        - { path: ^/parameter/customers$, roles: [ROLE_PROJECT_MANAGER, ROLE_RESPONSABLE, ROLE_ADMIN] }
        - { path: ^/parameter/customers/add, roles: ROLE_ADMIN }
        - { path: ^/parameter/customers/edit, roles: ROLE_ADMIN }
        - { path: ^/parameter/customers/delete, roles: ROLE_ADMIN }
        
        # Gestion des projets
        - { path: ^/parameter/projects$, roles: ROLE_PROJECT_MANAGER }
        
        # Configuration et administration
        - { path: ^/parameter/app_configuration, roles: ROLE_RESPONSABLE }
        - { path: ^/parameter/users/add, roles: ROLE_RESPONSABLE }
        - { path: ^/parameter/users/delete, roles: ROLE_RESPONSABLE }

# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            App\Entity\User: 'auto'
