# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Vous pouvez définir des paramètres globaux ici si nécessaire

services:
    # Configuration par défaut pour les services de l'application
    _defaults:
        autowire: true      # Permet l'injection automatique des dépendances
        autoconfigure: true # Configure automatiquement les services
    # Rend les classes de src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Services personnalisés
    App\Service\RoleHierarchyService:
        public: true

    App\Service\SecurityService:
        arguments:
            $security: '@security.helper'
            $passwordHasher: '@security.password_hasher'

    App\Service\PermissionService:
        arguments:
            $securityService: '@App\Service\SecurityService'
            $roleHierarchy: '@App\Service\RoleHierarchyService'

    # Service d'authentification personnalisé
    App\Security\AppCustomAuthenticator:
        arguments:
            $urlGenerator: '@router'
            $logger: '@logger'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
